# Assignment 2
# Task 1: NumPy Arrays and Data Analysis (similar to class activity 2)

In this activity you will practice working with NumPy arrays using a dataset of product sales across two stores over four weeks.

**Instructions:** Fill in the missing code wherever you see `# Your code here`.

In [1]:
import numpy as np

# Store A weekly sales: 4 weeks x 4 product categories
# Columns: Electronics, Clothing, Food, Toys
store_a = np.array([[320, 150, 480, 210],
                    [290, 175, 510, 195],
                    [410, 130, 460, 250],
                    [375, 160, 495, 230]])

# Store B weekly sales: 4 weeks x 4 product categories
store_b = np.array([[280, 200, 430, 190],
                    [310, 185, 450, 220],
                    [390, 170, 475, 205],
                    [350, 195, 440, 240]])

print("Store A Weekly Sales (rows=weeks, cols=Electronics/Clothing/Food/Toys):")
print(store_a)
print("\nStore B Weekly Sales (rows=weeks, cols=Electronics/Clothing/Food/Toys):")
print(store_b)

Store A Weekly Sales (rows=weeks, cols=Electronics/Clothing/Food/Toys):
[[320 150 480 210]
 [290 175 510 195]
 [410 130 460 250]
 [375 160 495 230]]

Store B Weekly Sales (rows=weeks, cols=Electronics/Clothing/Food/Toys):
[[280 200 430 190]
 [310 185 450 220]
 [390 170 475 205]
 [350 195 440 240]]


---
## Part 1: Statistical Analysis

Using `store_a`, complete the following tasks:

### Task 1.1: Calculate the overall mean of all sales in Store A

In [2]:

mean_all = np.mean(store_a)

print("Overall Mean Sales:", mean_all)

Overall Mean Sales: 302.5


### Task 1.2: Find the minimum and maximum sales values in Store A

In [3]:

min_sales =np.min(store_a)
max_sales =np.max(store_a)

print("Minimum Sales:", min_sales)
print("Maximum Sales:", max_sales)

Minimum Sales: 130
Maximum Sales: 510


### Task 1.3: Calculate the total sales per product category across all 4 weeks

*Hint: Use the `axis` parameter. axis=0 operates down columns (across rows), axis=1 operates across columns (across a single row).*

In [5]:

total_per_category = np.sum(store_a, axis=0)

print("Total sales per category (Electronics, Clothing, Food, Toys):", total_per_category)

Total sales per category (Electronics, Clothing, Food, Toys): [1395  615 1945  885]


### Task 1.4: Calculate the total sales per week (sum across all 4 product categories for each week)

In [6]:

total_per_week = np.sum(store_a, axis=1)

print("Total sales per week:", total_per_week)

Total sales per week: [1160 1170 1250 1260]


### Task 1.5: Calculate the variance and standard deviation of Store A sales

In [7]:

variance = np.var(store_a)
std_dev = np.std(store_a)

print("Variance:", variance)
print("Standard Deviation:", std_dev)

Variance: 16962.5
Standard Deviation: 130.24016277631105


---
## Part 2: Array Manipulation

Using `store_a`, complete the following tasks:

### Task 2.1: Reshape the array to have 8 rows and 2 columns

In [8]:

reshaped_8x2 = store_a.reshape(8,2)

print("Reshaped to 8x2:")
print(reshaped_8x2)

Reshaped to 8x2:
[[320 150]
 [480 210]
 [290 175]
 [510 195]
 [410 130]
 [460 250]
 [375 160]
 [495 230]]


### Task 2.2: Find the total number of elements in the array

In [9]:

total_elements = store_a.size

print("Total elements:", total_elements)

Total elements: 16


### Task 2.3: Flatten the array into a 1D array

In [10]:

flattened = store_a.flatten()

print("Flattened array:", flattened)

Flattened array: [320 150 480 210 290 175 510 195 410 130 460 250 375 160 495 230]


### Task 2.4: Transpose the array (swap rows and columns)

In [11]:

transposed = store_a.T

print("Transposed array:")
print(transposed)

Transposed array:
[[320 290 410 375]
 [150 175 130 160]
 [480 510 460 495]
 [210 195 250 230]]


### Task 2.5: Sort the flattened array in ascending order

*Hint: Use `np.sort()`*

In [12]:

sorted_array = np.sort(flattened)

print("Sorted sales values:", sorted_array)

Sorted sales values: [130 150 160 175 195 210 230 250 290 320 375 410 460 480 495 510]


---
## Part 3: Operations Between Two Arrays

Using both `store_a` and `store_b`, complete the following:

### Task 3.1: Add the two arrays element-wise to get combined sales

In [13]:

combined_sales = store_a + store_b

print("Combined Sales (Store A + Store B):")
print(combined_sales)

Combined Sales (Store A + Store B):
[[600 350 910 400]
 [600 360 960 415]
 [800 300 935 455]
 [725 355 935 470]]


### Task 3.2: Subtract Store B from Store A to see the sales difference per cell

In [14]:

sales_diff = store_a - store_b

print("Sales Difference (Store A - Store B):")
print(sales_diff)

Sales Difference (Store A - Store B):
[[ 40 -50  50  20]
 [-20 -10  60 -25]
 [ 20 -40 -15  45]
 [ 25 -35  55 -10]]


### Task 3.3: Use boolean indexing to find all cells in `store_a` where sales exceeded 400

In [16]:

high_sales = store_a[store_a > 400]

print("Sales values above 400:", high_sales)

Sales values above 400: [480 510 410 460 495]


### Task 3.4: Perform matrix multiplication between `store_a` and the transpose of `store_b`

*Hint: Use `np.dot()` and `.T` for transpose*

In [17]:

matrix_mult = np.dot(store_a, store_b.T)

print("Matrix Multiplication (A x B^T):")
print(matrix_mult)

Matrix Multiplication (A x B^T):
[[365900 389150 421350 402850]
 [372550 394675 425075 406825]
 [386100 413150 451750 431250]
 [393550 419200 455725 435450]]


---
## Part 4: Bonus Challenge

Try these if you finish early!

### Task 4.1: Normalize Store A sales to a 0-1 range

*Hint: normalized = (x - min) / (max - min)*

In [18]:
# Your code here
normalized = (store_a - np.min(store_a)) / (np.max(store_a) - np.min(store_a))

print("Normalized Store A Sales:")
print(normalized)

Normalized Store A Sales:
[[0.5        0.05263158 0.92105263 0.21052632]
 [0.42105263 0.11842105 1.         0.17105263]
 [0.73684211 0.         0.86842105 0.31578947]
 [0.64473684 0.07894737 0.96052632 0.26315789]]


### Task 4.2: Stack `store_a` and `store_b` vertically into a single 8x4 array

*Hint: Use `np.vstack()`*

In [19]:
# Your code here
stacked = np.vstack((store_a, store_b))

print("Vertically Stacked Array (8x4):")
print(stacked)
print("Shape:", stacked.shape)

Vertically Stacked Array (8x4):
[[320 150 480 210]
 [290 175 510 195]
 [410 130 460 250]
 [375 160 495 230]
 [280 200 430 190]
 [310 185 450 220]
 [390 170 475 205]
 [350 195 440 240]]
Shape: (8, 4)
